### ISSUE TITLE
Error building OPX: gbp:error: 'git-pbuilder' failed: it exited with 1

### ISSUE THREAD

**Issue by alimodarresi** [open-switch/opx-build#75]
Hi.
I have followed the instructions and built OPX 3.1.0 and I am getting this error multiple times:

 **W: /home/opx/.pbuilderrc does not exist**

and this error at the end:

gbp:error: 'git-pbuilder' failed: it exited with 1

can someone help me?

**Comment by gunasekaran-t** [comment]
@alimodarresi , could you confirm if you are still facing issue. In #76 you have mentioned that you are able to build the image. If the problem still exits please share the step followed.

**Comment by alimodarresi** [comment]
Hi @gunasekaran-t 
yes i am still facing this issue

**Comment by gunasekaran-t** [comment]
@alimodarresi Could you please share the steps you followed after checking out the repos. Preferably a log file.

**Comment by alimodarresi** [comment]
@gunasekaran-t  yes of course
I've downloaded source codes using 

repo init -u https://github.com/open-switch/opx-manifest && repo sync

and then I run the below command

sudo OPX_RELEASE=3.1.0 opx-build/scripts/opx_run opx_build all

and i am getting the mentioned error.
If i get more infoemation i will lert you know.
thanks for helping

**Comment by alimodarresi** [comment]
Hi @gunasekaran-t  
after running   

sudo opx-build/scripts/opx_run opx_rel_pkgasm.py --dist stable  -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml

i am getting these logs:


fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.2.0-stretch_amd64.tar.gz ...
tar_in(self, /tmp/tmpsMDJKk, /)
tar_in(['fakeroot', '-i', '/tmp/tmp2y7Ze5', '-s', '/tmp/tmp2y7Ze5', 'tar', '-C', '/tmp/tmpgVayMn/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
update_rootfs(self)
do_chroot(self, /opt/opx-build/scripts/templates/do_apt_upgrade_sh)
do_chroot
['fakechroot', 'fakeroot', '-i', '/tmp/tmp2y7Ze5', '-s', '/tmp/tmp2y7Ze5', '/usr/sbin/chroot', '/tmp/tmpgVayMn', '/do_apt_upgrade_sh']
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://deb.debian.org/debian stretch Release [118 kB]
Get:3 http://deb.debian.org/debian stretch Release.gpg [2365 B]
Get:4 http://deb.debian.org/debian stretch/main amd64 Packages [7086 kB]
Get:5 http://deb.debian.org/debian stretch/main Translation-en [5385 kB]                                                                                                                                    
Fetched 12.6 MB in 25s (495 kB/s)                                                                                                                                                                           
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dirmngr is already the newest version (2.1.18-8~deb9u4).
The following additional packages will be installed:
  krb5-locales libcurl3 libgssapi-krb5-2 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libnghttp2-14 librtmp1 libssh2-1
Suggested packages:
  krb5-doc krb5-user
The following NEW packages will be installed:
  curl krb5-locales libcurl3 libgssapi-krb5-2 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libnghttp2-14 librtmp1 libssh2-1
0 upgraded, 11 newly installed, 0 to remove and 31 not upgraded.
Need to get 1551 kB of archives.
After this operation, 3925 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 krb5-locales all 1.15-1+deb9u1 [93.8 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 libkeyutils1 amd64 1.5.9-9 [12.4 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 libkrb5support0 amd64 1.15-1+deb9u1 [61.9 kB]
Get:4 http://deb.debian.org/debian stretch/main amd64 libk5crypto3 amd64 1.15-1+deb9u1 [119 kB]
Get:5 http://deb.debian.org/debian stretch/main amd64 libkrb5-3 amd64 1.15-1+deb9u1 [311 kB]
Get:6 http://deb.debian.org/debian stretch/main amd64 libgssapi-krb5-2 amd64 1.15-1+deb9u1 [155 kB]
Get:7 http://deb.debian.org/debian stretch/main amd64 libnghttp2-14 amd64 1.18.1-1 [79.1 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-1+b1 [60.4 kB]                                                                                               
Get:9 http://deb.debian.org/debian stretch/main amd64 libssh2-1 amd64 1.7.0-1+deb9u1 [139 kB]                                                                                                               
Get:10 http://deb.debian.org/debian stretch/main amd64 libcurl3 amd64 7.52.1-5+deb9u9 [292 kB]                                                                                                              
Get:11 http://deb.debian.org/debian stretch/main amd64 curl amd64 7.52.1-5+deb9u9 [227 kB]                                                                                                                  
Fetched 1551 kB in 12s (123 kB/s)                                                                                                                                                                           
Selecting previously unselected package krb5-locales.
(Reading database ... 19605 files and directories currently installed.)
Preparing to unpack .../00-krb5-locales_1.15-1+deb9u1_all.deb ...
Unpacking krb5-locales (1.15-1+deb9u1) ...
Selecting previously unselected package libkeyutils1:amd64.
Preparing to unpack .../01-libkeyutils1_1.5.9-9_amd64.deb ...
Unpacking libkeyutils1:amd64 (1.5.9-9) ...
Selecting previously unselected package libkrb5support0:amd64.
Preparing to unpack .../02-libkrb5support0_1.15-1+deb9u1_amd64.deb ...
Unpacking libkrb5support0:amd64 (1.15-1+deb9u1) ...
Selecting previously unselected package libk5crypto3:amd64.
Preparing to unpack .../03-libk5crypto3_1.15-1+deb9u1_amd64.deb ...
Unpacking libk5crypto3:amd64 (1.15-1+deb9u1) ...
Selecting previously unselected package libkrb5-3:amd64.
Preparing to unpack .../04-libkrb5-3_1.15-1+deb9u1_amd64.deb ...
Unpacking libkrb5-3:amd64 (1.15-1+deb9u1) ...
Selecting previously unselected package libgssapi-krb5-2:amd64.
Preparing to unpack .../05-libgssapi-krb5-2_1.15-1+deb9u1_amd64.deb ...
Unpacking libgssapi-krb5-2:amd64 (1.15-1+deb9u1) ...
Selecting previously unselected package libnghttp2-14:amd64.
Preparing to unpack .../06-libnghttp2-14_1.18.1-1_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.18.1-1) ...
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../07-librtmp1_2.4+20151223.gitfa8646d.1-1+b1_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1+b1) ...
Selecting previously unselected package libssh2-1:amd64.
Preparing to unpack .../08-libssh2-1_1.7.0-1+deb9u1_amd64.deb ...
Unpacking libssh2-1:amd64 (1.7.0-1+deb9u1) ...
Selecting previously unselected package libcurl3:amd64.
Preparing to unpack .../09-libcurl3_7.52.1-5+deb9u9_amd64.deb ...
Unpacking libcurl3:amd64 (7.52.1-5+deb9u9) ...
Selecting previously unselected package curl.
Preparing to unpack .../10-curl_7.52.1-5+deb9u9_amd64.deb ...
Unpacking curl (7.52.1-5+deb9u9) ...
Setting up libnghttp2-14:amd64 (1.18.1-1) ...
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1+b1) ...
Setting up libssh2-1:amd64 (1.7.0-1+deb9u1) ...
Setting up krb5-locales (1.15-1+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up libkeyutils1:amd64 (1.5.9-9) ...
Setting up libkrb5support0:amd64 (1.15-1+deb9u1) ...
Setting up libk5crypto3:amd64 (1.15-1+deb9u1) ...
Setting up libkrb5-3:amd64 (1.15-1+deb9u1) ...
Setting up libgssapi-krb5-2:amd64 (1.15-1+deb9u1) ...
Setting up libcurl3:amd64 (7.52.1-5+deb9u9) ...
Setting up curl (7.52.1-5+deb9u9) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
sudo: unable to resolve host 6f897d87ee76
Executing: /tmp/apt-key-gpghome.Hb65mDxGux/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1
gpg: key 5EF20F36AD5073F1: "OpenSwitch <opx@openswitch.net>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  base-files dbus debian-archive-keyring libdbus-1-3 libdns-export162 libexpat1 libexpat1-dev libglib2.0-0 libglib2.0-data libicu57 libisc-export160 libldap-2.4-2 libldap-common libssl1.0.2 libssl1.1
  libsystemd0 libudev1 linux-libc-dev openssl patch python-cryptography python-pip python-pip-whl systemd systemd-sysv tzdata udev vim-common vim-tiny wget xxd
31 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.8 MB of archives.
After this operation, 98.3 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 base-files amd64 9.9+deb9u11 [67.5 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 libsystemd0 amd64 232-25+deb9u12 [282 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 systemd amd64 232-25+deb9u12 [2469 kB]
Get:4 http://deb.debian.org/debian stretch/main amd64 udev amd64 232-25+deb9u12 [1113 kB]                                                                                                                   
Get:5 http://deb.debian.org/debian stretch/main amd64 libudev1 amd64 232-25+deb9u12 [126 kB]                                                                                                                
Get:6 http://deb.debian.org/debian stretch/main amd64 systemd-sysv amd64 232-25+deb9u12 [82.5 kB]                                                                                                           
Get:7 http://deb.debian.org/debian stretch/main amd64 debian-archive-keyring all 2017.5+deb9u1 [73.9 kB]                                                                                                    
Get:8 http://deb.debian.org/debian stretch/main amd64 tzdata all 2019b-0+deb9u1 [275 kB]                                                                                                                    
Get:9 http://deb.debian.org/debian stretch/main amd64 libssl1.0.2 amd64 1.0.2s-1~deb9u1 [1302 kB]                                                                                                           
Get:10 http://deb.debian.org/debian stretch/main amd64 libssl1.1 amd64 1.1.0k-1~deb9u1 [1356 kB]                                                                                                            
Get:11 http://deb.debian.org/debian stretch/main amd64 xxd amd64 2:8.0.0197-4+deb9u3 [132 kB]                                                                                                               
Get:12 http://deb.debian.org/debian stretch/main amd64 vim-tiny amd64 2:8.0.0197-4+deb9u3 [446 kB]                                                                                                          
Get:13 http://deb.debian.org/debian stretch/main amd64 vim-common all 2:8.0.0197-4+deb9u3 [159 kB]                                                                                                          
Get:14 http://deb.debian.org/debian stretch/main amd64 wget amd64 1.18-5+deb9u3 [800 kB]                                                                                                                    
Get:15 http://deb.debian.org/debian stretch/main amd64 dbus amd64 1.10.28-0+deb9u1 [212 kB]                                                                                                                 
Get:16 http://deb.debian.org/debian stretch/main amd64 libdbus-1-3 amd64 1.10.28-0+deb9u1 [195 kB]                                                                                                          
Get:17 http://deb.debian.org/debian stretch/main amd64 libexpat1-dev amd64 2.2.0-2+deb9u2 [134 kB]                                                                                                          
Get:18 http://deb.debian.org/debian stretch/main amd64 libexpat1 amd64 2.2.0-2+deb9u2 [83.6 kB]                                                                                                             
Get:19 http://deb.debian.org/debian stretch/main amd64 libldap-common all 2.4.44+dfsg-5+deb9u3 [85.7 kB]                                                                                                    
Get:20 http://deb.debian.org/debian stretch/main amd64 libldap-2.4-2 amd64 2.4.44+dfsg-5+deb9u3 [220 kB]                                                                                                    
Get:21 http://deb.debian.org/debian stretch/main amd64 libisc-export160 amd64 1:9.10.3.dfsg.P4-12.3+deb9u5 [335 kB]                                                                                         
Get:22 http://deb.debian.org/debian stretch/main amd64 libdns-export162 amd64 1:9.10.3.dfsg.P4-12.3+deb9u5 [852 kB]                                                                                         
Get:23 http://deb.debian.org/debian stretch/main amd64 libglib2.0-0 amd64 2.50.3-2+deb9u1 [2691 kB]                                                                                                         
Get:24 http://deb.debian.org/debian stretch/main amd64 libglib2.0-data all 2.50.3-2+deb9u1 [2518 kB]                                                                                                        
Get:25 http://deb.debian.org/debian stretch/main amd64 libicu57 amd64 57.1-6+deb9u3 [7705 kB]                                                                                                               
Get:26 http://deb.debian.org/debian stretch/main amd64 linux-libc-dev amd64 4.9.189-3 [1446 kB]                                                                                                             
Get:27 http://deb.debian.org/debian stretch/main amd64 openssl amd64 1.1.0k-1~deb9u1 [747 kB]                                                                                                               
Get:28 http://deb.debian.org/debian stretch/main amd64 patch amd64 2.7.5-1+deb9u2 [112 kB]                                                                                                                  
Get:29 http://deb.debian.org/debian stretch/main amd64 python-cryptography amd64 1.7.1-3+deb9u1 [211 kB]                                                                                                    
Get:30 http://deb.debian.org/debian stretch/main amd64 python-pip all 9.0.1-2+deb9u1 [179 kB]                                                                                                               
Get:31 http://deb.debian.org/debian stretch/main amd64 python-pip-whl all 9.0.1-2+deb9u1 [1399 kB]                                                                                                          
Fetched 27.8 MB in 1min 2s (446 kB/s)                                                                                                                                                                       
Extracting templates from packages: 100%
Preconfiguring packages ...
Can't exec "/tmp/libssl1.0.2.config.4y07AF": Exec format error at /usr/share/perl/5.24/IPC/Open3.pm line 178.
open2: exec of /tmp/libssl1.0.2.config.4y07AF configure 1.0.2q-1~deb9u1 failed: Exec format error at /usr/share/perl5/Debconf/ConfModule.pm line 59.
(Reading database ... 19691 files and directories currently installed.)
Preparing to unpack .../base-files_9.9+deb9u11_amd64.deb ...
Unpacking base-files (9.9+deb9u11) over (9.9+deb9u8) ...
Setting up base-files (9.9+deb9u11) ...
Installing new version of config file /etc/debian_version ...
(Reading database ... 19691 files and directories currently installed.)
Preparing to unpack .../libsystemd0_232-25+deb9u12_amd64.deb ...
Unpacking libsystemd0:amd64 (232-25+deb9u12) over (232-25+deb9u8) ...
Setting up libsystemd0:amd64 (232-25+deb9u12) ...
(Reading database ... 19691 files and directories currently installed.)
Preparing to unpack .../systemd_232-25+deb9u12_amd64.deb ...
Unpacking systemd (232-25+deb9u12) over (232-25+deb9u8) ...
Preparing to unpack .../udev_232-25+deb9u12_amd64.deb ...
Unpacking udev (232-25+deb9u12) over (232-25+deb9u8) ...
Preparing to unpack .../libudev1_232-25+deb9u12_amd64.deb ...
Unpacking libudev1:amd64 (232-25+deb9u12) over (232-25+deb9u8) ...
Setting up libudev1:amd64 (232-25+deb9u12) ...
Setting up systemd (232-25+deb9u12) ...
systemd-machine-id-setup: error while loading shared libraries: libsystemd-shared-232.so: cannot open shared object file: No such file or directory
dpkg: error processing package systemd (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
filter_packages(self)
installed_packages(self)
installed_packages
['fakechroot', 'fakeroot', '/usr/sbin/chroot', '/tmp/tmpgVayMn', 'apt', 'list', '--installed']

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

dpkg-scanpackages: info: Wrote 61 entries to output Packages file.
add_packages(self)
Sysroot is in /tmp/tmpgVayMn
Using http://deb.debian.org/debian stretch main
Using http://deb.debian.org/debian stretch-backports main
Using http://security.debian.org/debian-security stretch/updates main
Get:1 http://deb.debian.org/debian stretch/main amd64 libxau6 amd64 1:1.0.8-1 [20.7 kB]                                                                                                                     
Get:2 http://deb.debian.org/debian stretch/main amd64 libedit2 amd64 3.1-20160903-3 [84.8 kB]                                                                                                               
Get:3 http://deb.debian.org/debian stretch/main amd64 libopts25 amd64 1:5.18.12-3 [68.0 kB]                                                                                                                 
Get:4 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 tcpdump amd64 4.9.3-1~deb9u1 [391 kB]                                                                                       
Get:5 http://deb.debian.org/debian stretch/main amd64 ntp amd64 1:4.2.8p10+dfsg-3+deb9u2 [599 kB]                                                                                                           
Get:6 http://deb.debian.org/debian stretch/main amd64 gettext-base amd64 0.19.8.1-2+deb9u1 [122 kB]                                                                                                         
Get:7 http://deb.debian.org/debian stretch/main amd64 libevent-2.0-5 amd64 2.0.21-stable-3 [152 kB]                                                                                                         
Get:8 http://deb.debian.org/debian stretch/main amd64 libpci3 amd64 1:3.5.2-1 [56.5 kB]                                                                                                                     
Get:9 http://deb.debian.org/debian stretch/main amd64 libwrap0 amd64 7.6.q-26 [58.2 kB]                                                                                                                     
Get:10 http://deb.debian.org/debian stretch/main amd64 openssh-client amd64 1:7.4p1-10+deb9u7 [780 kB]                                                                                                      
Get:11 http://deb.debian.org/debian stretch/main amd64 ucf all 3.0036 [70.2 kB]                                                                                                                             
Get:12 http://deb.debian.org/debian stretch/main amd64 libdevmapper-event1.02.1 amd64 2:1.02.137-2 [41.6 kB]                                                                                                
Get:13 http://deb.debian.org/debian stretch/main amd64 liblvm2cmd2.02 amd64 2.02.168-2 [683 kB]                                                                                                             
Get:14 http://deb.debian.org/debian stretch/main amd64 dmeventd amd64 2:1.02.137-2 [59.5 kB]                                                                                                                
Get:15 http://deb.debian.org/debian stretch/main amd64 fonts-dejavu-core all 2.37-1 [1068 kB]                                                                                                               
Get:16 http://deb.debian.org/debian stretch/main amd64 fontconfig-config all 2.11.0-6.7 [271 kB]                                                                                                            
Get:17 http://deb.debian.org/debian stretch/main amd64 libpng16-16 amd64 1.6.28-1+deb9u1 [280 kB]                                                                                                           
Get:18 http://deb.debian.org/debian stretch/main amd64 libfreetype6 amd64 2.6.3-3.2 [438 kB]                                                                                                                
Get:19 http://deb.debian.org/debian stretch/main amd64 libfuse2 amd64 2.9.7-1+deb9u2 [126 kB]                                                                                                               
Get:20 http://deb.debian.org/debian stretch/main amd64 grub-common amd64 2.02~beta3-5+deb9u2 [2174 kB]                                                                                                      
Get:21 http://deb.debian.org/debian stretch/main amd64 grub2-common amd64 2.02~beta3-5+deb9u2 [528 kB]                                                                                                      
Get:22 http://deb.debian.org/debian stretch/main amd64 ifenslave all 2.9 [16.0 kB]                                                                                                                          
Get:23 http://deb.debian.org/debian stretch/main amd64 libklibc amd64 2.0.4-9 [52.6 kB]                                                                                                                     
Get:24 http://deb.debian.org/debian stretch/main amd64 klibc-utils amd64 2.0.4-9 [108 kB]                                                                                                                   
Get:25 http://deb.debian.org/debian stretch/main amd64 initramfs-tools-core all 0.130 [97.0 kB]                                                                                                             
Get:26 http://deb.debian.org/debian stretch/main amd64 linux-base all 4.5 [19.1 kB]                                                                                                                         
Get:27 http://deb.debian.org/debian stretch/main amd64 initramfs-tools all 0.130 [66.0 kB]                                                                                                                  
Get:28 http://deb.debian.org/debian stretch/main amd64 libfontconfig1 amd64 2.11.0-6.7+b1 [331 kB]                                                                                                          
Get:29 http://deb.debian.org/debian stretch/main amd64 libhiredis0.13 amd64 0.13.3-2 [27.7 kB]                                                                                                              
Get:30 http://deb.debian.org/debian stretch/main amd64 libjansson4 amd64 2.9-1 [28.1 kB]                                                                                                                    
Get:31 http://deb.debian.org/debian stretch/main amd64 libjpeg62-turbo amd64 1:1.5.1-2 [134 kB]                                                                                                             
Get:32 http://deb.debian.org/debian stretch/main amd64 liblvm2app2.2 amd64 2.02.168-2 [554 kB]                                                                                                              
Get:33 http://deb.debian.org/debian stretch/main amd64 libpcap0.8 amd64 1.8.1-3 [138 kB]                                                                                                                    
Get:34 http://deb.debian.org/debian stretch/main amd64 libreadline5 amd64 5.2+dfsg-3+b1 [119 kB]                                                                                                            
Get:35 http://deb.debian.org/debian stretch/main amd64 libsensors4 amd64 1:3.4.0-4 [53.3 kB]                                                                                                                
Get:36 http://deb.debian.org/debian stretch/main amd64 libsnmp-base all 5.7.3+dfsg-1.7+deb9u1 [1595 kB]                                                                                                     
Get:37 http://deb.debian.org/debian stretch/main amd64 libsnmp30 amd64 5.7.3+dfsg-1.7+deb9u1 [2332 kB]                                                                                                      
Get:38 http://deb.debian.org/debian stretch/main amd64 libsnmp-perl amd64 5.7.3+dfsg-1.7+deb9u1 [1498 kB]                                                                                                   
Get:39 http://deb.debian.org/debian stretch/main amd64 libxdmcp6 amd64 1:1.1.2-3 [26.3 kB]                                                                                                                  
Get:40 http://deb.debian.org/debian stretch/main amd64 libxcb1 amd64 1.12-1 [133 kB]                                                                                                                        
Get:41 http://deb.debian.org/debian stretch/main amd64 libx11-data all 2:1.6.4-3+deb9u1 [287 kB]                                                                                                            
Get:42 http://deb.debian.org/debian stretch/main amd64 libx11-6 amd64 2:1.6.4-3+deb9u1 [748 kB]                                                                                                             
Get:43 http://deb.debian.org/debian stretch/main amd64 libxrender1 amd64 1:0.9.10-1 [33.0 kB]                                                                                                               
Get:44 http://deb.debian.org/debian stretch/main amd64 libxft2 amd64 2.3.2-1+b2 [56.5 kB]                                                                                                                   
Get:45 http://deb.debian.org/debian stretch/main amd64 lldpd amd64 0.9.6-1 [199 kB]                                                                                                                         
Get:46 http://deb.debian.org/debian stretch/main amd64 lvm2 amd64 2.02.168-2 [933 kB]                                                                                                                       
Get:47 http://deb.debian.org/debian stretch/main amd64 net-tools amd64 1.60+git20161116.90da8a0-1 [248 kB]                                                                                                  
Get:48 http://deb.debian.org/debian stretch/main amd64 openssh-sftp-server amd64 1:7.4p1-10+deb9u7 [39.5 kB]                                                                                                
Get:49 http://deb.debian.org/debian stretch/main amd64 openssh-server amd64 1:7.4p1-10+deb9u7 [332 kB]                                                                                                      
Get:50 http://deb.debian.org/debian stretch/main amd64 perl-tk amd64 1:804.033-1+b3 [1943 kB]                                                                                                               
Get:51 http://deb.debian.org/debian stretch/main amd64 tkmib all 5.7.3+dfsg-1.7+deb9u1 [1471 kB]                                                                                                            
Get:52 http://deb.debian.org/debian stretch/main amd64 iproute all 1:4.9.0-1+deb9u1 [16.6 kB]                                                                                                               
Get:53 http://deb.debian.org/debian stretch/main amd64 vlan amd64 1.9-3.2+b1 [36.9 kB]                                                                                                                      
Get:54 http://deb.debian.org/debian stretch/main amd64 watchdog amd64 5.15-2 [90.3 kB]                                                                                                                      
Fetched 21.8 MB in 6s (78.7 kB/s)                                                                                                                                                                           
Sysroot is in /tmp/tmpgVayMn
Using copy:/mnt stable main
Using http://deb.openswitch.net/stretch stable main opx opx-non-free
Using http://deb.debian.org/debian stretch main
Using http://security.debian.org/debian-security stretch/updates main
Using http://deb.debian.org/debian stretch-updates main
Get:1 http://deb.openswitch.net/stretch stable/opx-non-free amd64 linux-image-4.9.110 amd64 4.9.110-3+deb9u4-99999 [38.5 MB]                                                                                
Fetched 38.5 MB in 6s (219 kB/s)                                                                                                                                                                            
Sysroot is in /tmp/tmpgVayMn
Using copy:/mnt stable main
Using http://deb.openswitch.net/stretch stable main opx opx-non-free
Using http://deb.debian.org/debian stretch main
Using http://security.debian.org/debian-security stretch/updates main
Using http://deb.debian.org/debian stretch-updates main
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1353, in main
    rel_plan.add_packages()
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 946, in add_packages
    packer.fetch(names=deb_package_list)
  File "/opt/opx-build/scripts/opx_get_packages.py", line 475, in fetch
    from_user=False)
  File "/usr/lib/python2.7/dist-packages/apt/package.py", line 1309, in mark_install
    fixer.resolve(True)
opx_get_packages.OpxPackagesError: E:Unable to correct problems, you have held broken packages.

**Comment by disaster123** [comment]
The current opx release is still tagged unstable since month. Have you tried to build using unstable?

**Comment by alimodarresi** [comment]
Hi @disaster123
yes i have tried that and i have built successfully using that.
but i am wondering what is the difference between stable and unstable?
and why i can't build using stable tag?

if you can help me i will appreciate it.
thanks

**Comment by disaster123** [comment]
ASK dell but as far as I know stable is outdated and no longer supported. Somebody at dell has missed to move the last release from unstable to stable

**Comment by alimodarresi** [comment]
Thanks for your time sir.

**Comment by gunasekaran-t** [comment]
@disaster123 Thanks for helping out. 
Yes it seems there are few things missed for last few releases. Will try to sort it out upcoming releases. 

@alimodarresi meanwhile please -dist 3.2.0 or -dist unstable for opx_rel_pkgasm.py. 3.2.0 worked for me.

**Comment by mikelazar** [comment]
Assuming that this is taken care of (e.g. use --dist 3.2.0). Please reopen (or open another issue) if there are still problems.

**Comment by gunasekaran-t** [comment]
With release 3.2.1 stable distribution also should compile fine.
