### ISSUE TITLE
Instructions out of date?

### ISSUE THREAD

**Issue by grantcurell** [open-switch/opx-build#79]
It looks like the instructions are out of date. Ex:

```
[root@r440 ~]# opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable   -b opx-onie-installer/release_bp/OPX_dell_base.xml
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1343, in main
    with open(args.b, 'r') as fd_:
IOError: [Errno 2] No such file or directory: 'opx-onie-installer/release_bp/OPX_dell_base.xml'
```

When I go and check my blueprints I see:

```
[root@r440 ~]# ls -al opx-onie-installer/release_bp/
total 60
drwxr-xr-x. 4 root root 4096 Jun 27 22:08 .
drwxr-xr-x. 9 root root  207 Jun 27 22:08 ..
-rw-r--r--. 1 root root 7455 Jun 27 22:08 blueprint.xsd
-rw-r--r--. 1 root root  978 Jun 27 22:08 opx_debian_base_stretch.xml
-rw-r--r--. 1 root root  998 Jun 27 22:08 opx_debian_base.xml
-rw-r--r--. 1 root root 3207 Jun 27 22:08 OPX_dell_base_jessie.xml
-rw-r--r--. 1 root root 4169 Jun 27 22:08 OPX_dell_base_stretch.xml
-rw-r--r--. 1 root root  954 Jun 27 22:08 OPX_dell_kernel_only_stretch.xml
-rw-r--r--. 1 root root  867 Jun 27 22:08 OPX_dell_kernel_only.xml
-rw-r--r--. 1 root root 1935 Jun 27 22:08 OPX_edgecore_base_stretch.xml
-rw-r--r--. 1 root root 1902 Jun 27 22:08 OPX_edgecore_base.xml
drwxr-xr-x. 2 root root 4096 Jun 27 22:08 repo
-rw-r--r--. 1 root root  197 Jun 27 22:08 rootfs_jessie.xml
-rw-r--r--. 1 root root  199 Jun 27 22:08 rootfs_stretch.xml
drwxr-xr-x. 5 root root   65 Jun 27 22:08 vendor
```

I just started troubleshooting, but at a glance running the assembly process fails:

```
[root@r440 ~]# opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable   -b opx-onie-installer/release_bp/opx_debian_base_stretch.xml
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1344, in main
    rel_blueprint = OpxRelBlueprint.load_xml(fd_, args.dist)
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 659, in load_xml
    return OpxRelBlueprint.fromElement(root, dist)
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 562, in fromElement
    description = elem.find('description').text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by grantcurell** [comment]
Pull request to address this added here: https://github.com/open-switch/opx-build/pull/81
